env:
  global:
    - secure: k7mudHYh6AqHueWEI9MxbxK9yKB7bNJyEzDRIwr8RoYYZ0H0v6VwoTvy9IlZldSmKD/XeOVhTPqtKLFN9DGvfPODGCQgrYFbyMDaN7nCHE/1dXv+ePecYF2k+WFP/9g1QF1E1Z2AicWEyjgbfuoVmeaM9MyqRcsOA8CnMkblIHl+m/eD6TEwyZHCsM2VNARH5Ukndg0zdjPQPTmZ4K6T3VrheETo0bImS8MHXrXPmIusnbr6y2Vmbthp9pr6TKaqv4uboV9KWgCEneuGniivmdVaausjgyhkMrPZ/X0s7IRzi6F8UyHwYeMEeXYBEh3ztYAze5g4w24jwzEaKYAqn5u/ZF7OP4j2NAmxrEPmcIJ6dmktZyK+tmuhu+0eU9Q1UAeiY3Wky40Io0wACbVAqjzzhUvWfj289KB1GdpuayFuzaJAIozmWJvNjbGsNy+kswKPp7yFFLQQFFTvZ4sk1ymGaz/+QsqPm5sD6ePMhx4k2WrYpSQzaBKDr1X6ur/pEJJ+kPOZ14sHbAGy5UWvqPIbFkr1iC1G/2ACt/pyXfqtz/yHyZLJrWgWRxuZzCOeR4B4FNS1caM4chgYR0UG3myLEOz7ZnryHKNUJwWsd/PeyGyc8sMJCND/VY2tq5sZfqwKz2JOgg38NUzGlcRr49i9+CG4XuABDKl6EG6m8aQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/antipopads
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
