env:
  global:
    - secure: DPCadMsuVoW3l3+ZFb3QDBbH5l0pYgRScdyZ6oodaNz6kpTyvBpO7y85Oj3YdDvio38JiI7SwlKoTbKHxIG6cx+ka366shR94x2EyikMRf9tpF7uvEnnr003QsEuYp1ghguYIbZNGKIUtS8Ow15IPu1fwZaaZFt60gOWgUi3RwS9MkTNgM0zGJn+cWTNe18njtKb3mU5LhirEGyjrELqPlgcXwXsG3YqaAhFv6Lc8/FepcM6Jfz0eVEZnCk+2BYIpErtA/2rQvhGEsC1CaSSAeZhmFy6bpChJFToHgwsqTyFR+kIWl011GeeW79Qbtz8Cuqa8GI/S237JSsNGyzOMg7JBSwxv5oII5axOKFk5e4I3cPEdIirEY7a1DNspDBw34dWZJbdbkxRFYmakpkxw+MtEGxE5Ko4/9GeTdX+eLDMPgcynbzTqo6Fv3f9vxd5E1WwJdUKbQuE2hqtVMjtG2XJfj6gmeqgsDOLfGAoBWxovRCt11xNoLoXkJNKs6pY8/H8AE6VTjMFykc2pVYSuAT8K9/Dv/y13dOKEXdzZZx6iHwYkM2Rlupw6caEWn5n60k1zYkoyDJPGzKOvJa/QZHR895MYsfMIrfx73rDnhnnWE+qntz+zUqDd4m/JoeUwIQIAHU06JXnD7nKRyyyNYipieX8EnSehpwTMTQnRNI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/antipopads
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
