env:
  global:
    - secure: pnsGcywgHGnhd5r5zGEVEr+A/uqhfJrzr549Z0QaWb/P3nwXtM6suhXddI5jf3LfJQW73g2AuRnzhaGJx3GaSJABSksEwWDzrv3sudPr5N+uPJcQPO4NpyTe2mzytCHz7zLK/Ubklaa7/T53Tp9h+37FPIx2oOI/Vlfcwc/DR4j2guZy/VQoX99zMOcs9V+2zQfpAZlCfRiwDJNykUuZ9wr3O3vCu133r2PaZ1Do/tOnR/lUlq8E96WLI5N7YnbF26CVNzudW9y9usbb5guysycBz9yB+ZrjhU4Uj2CoMQJ++HoHeBq+O2yuGDQQyGe1eL50KHcxpUY4fvG3tIhzvSS6bGb+efSZxxgtihnbzhldvT6A45TDoTMDzDanEsDPTAbBsdtcpZLMUGcc7u+EVd6aYyRcAHav4chrjLNgD1OoygfQyX53Kxuj+F0Fk+5wzUbtyYYOgCDNvP956pd52fmkMXRd0foq5iQQS8okwR9kzgmAxrvBf+UA6gcQRWyRbtbRmpwKKVojLt9VJPu9x5O/4l2+uUznO53kOtmiZ84BwP8cKKw/GhaTQ3nPAYNvLCpM+JP0+TxCJuLEI7AUoiuoFzipz7IYEYl62Y/fM4vsm2CuMdCfnneKhe1cBQaaWmun0rBn0fgbQ4DbD+02vJ0n7li7EBGraTCtcfQNwSw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/antipopads
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
