env:
  global:
    - secure: OrK5cRSu8BqUNPV1uPJOw4BbsBLCO2XjPUo7LdCvP+oEXxPG3MTDIab2oAdd9Btilo4P0B5dsVaW5lw0kbJHNuMchwglrD7irBqx0qEoYGzY+IEuUT2tgihzaZRS/JbMTLb+d6YXmvvpaJQG4mYFe5q4Ch3irM/GHL9/phkvWyCQDvHXw0eeQn77ZXQ4L3MPWxoTl2Uc7yjKun6Z94dWlL33L+xHqXipxMCD/Dm10JW2bkzwp6gac97OWQUN9XAafLhwkdhR+DQ5Q9I/QLJvSfr0JQj8UqXt9LwyrBkJVWVTOfpXUuZByIfP+nkVBjJMGFGCJw7GVVWhw54uGMsO0+cxZsXhEAH5E8HvzdjkuDCX7BQxLL4XeO6tDz0/GFIKKos0IfX6xcMCXXP+onng6eFCPfsos04mMCrkAjYB+Hf62ECFplwFpKw2Xm5Q4T595r+XiAR2fKR9da3CWOXW4GU4IkLiyGRYrKQtAPRG2HSmPo4lWEhdh//X3Ks2DtiS7VIO4r6z4YFrXajU6xrQ12iFo8IzI7Wy0uazt3CD6O0nt/Vc9Vrdu29B5OtioHvkThuBQPwoz8MbIpFW9otdfZ/opcoMFtoHeYosnr1I+tzjJqPnicOEiWTRSn13zyifwa3NkthTe6SXQylDBevZD21ELbtH7Q2sIfe4HUjzZXk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/antipopads
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
